version: '3.9'

services:
  reverse-proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx:stable-alpine
    container_name: reverse-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      # - "443:443" # opcjonalnie, jeśli robisz TLS
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      # - ./certs:/etc/nginx/certs
    # depends_on:
    #   - gateway
    networks:
      - shared

networks:
  shared:
    external: true
