version: '3.9'

services:
  redis:
    image: redis:7.4.0-alpine
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    # logging:
    #   driver: json-file
    #   options:
    #     max-size: "10m"

volumes:
  redis-data:

networks:
  shared:
    external: true
