version: '3.9'

services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "8080:80"
    volumes:
      - pgadmindata:/var/lib/pgadmin
    networks:
      - shared

volumes:
  pgadmindata:

networks:
  shared:
    external: true
